application: foundation-toolkit
version: 0-0-4
runtime: python
api_version: 1

handlers:
- url: /workers
  static_dir: workers/
  mime_type: application/x-gears-worker

- url: /scripts
  static_dir: scripts/

- url: /lib
  static_dir: lib/

- url: /tools
  static_dir: tools/

- url: /site-manifest.txt
  static_files: site-manifest.txt
  upload: site-manifest.txt

- url: /.*
  script: ftk.py
