application: foundation-toolkit
version: 0-0-4
runtime: python
api_version: 1

handlers:
- url: /workers/loader.worker.js
  static_files: workers/loader.worker.js
  upload: workers/loader.worker.js
  mime_type: application/x-gears-worker

- url: /scripts
  static_dir: scripts/

- url: /lib
  static_dir: lib/

- url: /tools
  static_dir: tools/

- url: /html
  static_dir: html/

- url: /site-manifest.txt
  static_files: site-manifest.txt
  upload: site-manifest.txt

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /.*
  script: ftk.py
